---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for Nextcloud
  template: src=default.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx

- ufw:
    state: enabled
    rule: allow
    port: 80
    proto: tcp
