---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for Nextcloud
  template: src=default.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx

- ufw:
    state: enabled
    rule: allow
    port: 80
    proto: tcp

- name: Remove the default html folder
  file:
    state: absent
    path: /var/www/html

- name: Copy privacybox welcome page
  template: src=index.html dest=/var/www/
