---
- name: Install nginx
  apt: name=nginx state=present
  become: yes

- name: Copy default Nginx configuration
  template: src=default.conf dest=/etc/nginx/sites-available/default
  become: yes
  notify: reload nginx

- ufw:
    state: enabled
    rule: allow
    port: 80
    proto: tcp
  become: yes

- ufw:
    state: enabled
    rule: allow
    port: 443
    proto: tcp
  become: yes

- name: Remove the default html folder
  file:
    path: /var/www/html
    state: absent
  become: yes

- name: Create Web Root
  file:
    path: '{{ docroot }}'
    state: directory
    owner: www-data
    group: www-data
  become: yes

- name: Copy privacybox welcome page
  template: src=index.html dest=/var/www/
  become: yes
  notify:
  - fix webroot permissions
  - reload nginx
