---
# Which version of Nextcloud to deploy
nc_version: '18.0.1'
nc_sha256sum: 770faf34b8f0d81273623daed4d64ec7919c38dfeb07328b613058addbed19c0

# These are the Nextcloud database settings
nc_db_name: nextcloud
nc_db_user: nextcloud
nc_db_password: secret
