---
- name: Add Sury signing key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- lineinfile:
    path: /etc/apt/sources.list
    line: 'deb https://packages.sury.org/php/ stretch main'

- name: Install php-fpm and deps
  apt:
    update_cache: yes
    pkg:
      - php7.4-dev
      - php7.4-cli
      - php7.4-fpm
      - php7.4-zip
      - php7.4-mbstring
      - php7.4-gd
      - php7.4-xml
      - php7.4-intl
      - php7.4-json
      - php7.4-sqlite3
      - php7.4-mysql
      - php7.4-curl
      - php7.4-tidy
      - php7.4-bcmath
      - php7.4-ldap
      - php-redis
      - php-imagick
    state: present

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm
#
# - name: Copy php-fpm configuration
#   template: src=nextcloud.conf dest=/etc/php-fpm.d/
#   notify: restart php-fpm

# FPM
- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.enable
    value: 1

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.enable_cli
    value: 1

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.memory_consumption
    value: 128

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.interned_strings_buffer
    value: 8

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.max_accelerated_files
    value: 10000

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.revalidate_freq
    value: 1

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: opcache
    option: opcache.save_comments
    value: 1

- ini_file:
    path: /etc/php/7.4/fpm/php.ini
    section: PHP
    option: memory_limit
    value: 1024M

#  CLI
- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.enable
    value: 1

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.enable_cli
    value: 1

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.memory_consumption
    value: 128

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.interned_strings_buffer
    value: 8

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.max_accelerated_files
    value: 10000

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.revalidate_freq
    value: 1

- ini_file:
    path: /etc/php/7.4/cli/php.ini
    section: opcache
    option: opcache.save_comments
    value: 1

# - name: Link fpm and cli ini configs
#   file: path=/etc/php/7.4/cli/php.ini
#         src=/etc/php/7.4/fpm/php.ini
#         state=link
#         force=yes
#   notify: restart php-fpm

- name: Ensure PHP environment variables are available
  lineinfile:
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    regexp: ;env[PATH] = /usr/local/bin:/usr/bin:/bin
    line: env[PATH] = /usr/local/bin:/usr/bin:/bin
  notify: restart php-fpm

- name: Fetch Composer setup
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: Check setup validity
  command: php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

- name: Build Composer
  command: php composer-setup.php

- name: Move binary
  command: mv composer.phar /usr/local/bin/composer
  become: yes

- name: Unlink
  command: php -r "unlink('composer-setup.php');"

- name: Copy phpinfo
  template: src=phpinfo.php dest=/var/www/



