---
- name: Add Sury signing key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- lineinfile:
    path: /etc/apt/sources.list
    line: 'deb https://packages.sury.org/php/ stretch main'

- name: Install php-fpm and deps
  apt:
    update_cache: yes
    pkg:
      - php7.3-dev
      - php7.3-cli
      - php7.3-fpm
      - php7.3-zip
      - php7.3-mbstring
      - php-redis
      - php7.3-gd
      - php7.3-xml
      - php7.3-intl
      - php7.3-json
      - php7.3-sqlite3
      - php7.3-mysql
      - php7.3-curl
      - php7.3-tidy
      - php7.3-bcmath
      - php-imagick
      - composer
    state: present

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm
#
# - name: Copy php-fpm configuration
#   template: src=nextcloud.conf dest=/etc/php-fpm.d/
#   notify: restart php-fpm

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.enable
    value: 1

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.enable_cli
    value: 1

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.interned_strings_buffer
    value: 8

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.max_accelerated_files
    value: 10000

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.memory_consumption
    value: 128

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.save_comments
    value: 1

- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: opcache
    option: opcache.revalidate_freq
    value: 1

- name: Link fpm and cli ini configs
  file: path=/etc/php/7.3/cli/php.ini
        src=/etc/php/7.3/fpm/php.ini
        state=link
        force=yes
  notify: restart php-fpm

- name: Ensure PHP environment variables are available
  lineinfile:
    dest: /etc/php/7.3/fpm/pool.d/www.conf
    regexp: ;env[PATH] = /usr/local/bin:/usr/bin:/bin
    line: env[PATH] = /usr/local/bin:/usr/bin:/bin
  notify: restart php-fpm

- name: Copy phpinfo
  template: src=phpinfo.php dest=/var/www/
