---
- name: Make sure Firefly-iii path does not yet exist
  file:
    state: absent
    path: /var/www/firefly-iii

- name: Clone Firefly-iii from Github
  git: repo=https://github.com/firefly-iii/firefly-iii.git dest=/var/www/firefly-iii
  become: yes
  become_user: www-data

# - name: Add group "firefly-iii"
#   group: name=firefly-iii
#
# - name: Add user "firefly-iii"
#   user: name=firefly-iii group=firefly-iii home=/var/www/firefly-iii/

- name: Create Firefly-iii database
  mysql_db: name={{ wb_db_name }} state=present

- name: Create Firefly-iii database user
  mysql_user: name={{ wb_db_user }} password={{ wb_db_password }} priv={{ wb_db_name }}.*:ALL host='localhost' state=present

- name: Composer install dependencies
  command: chdir=/var/www/firefly-iii composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.7.10
  become: yes
  become_user: www-data

  php artisan migrate:refresh --seed
php artisan firefly:upgrade-database
php artisan firefly:verify
php artisan passport:install

- name: Copy Firefly-iii server block
  template: src=nginx.conf dest=/etc/nginx/sites-available/finance.{{ privacybox_domain }}.conf

- name: setup nginx symlinks
  file: path=/etc/nginx/sites-enabled/finance.{{ privacybox_domain }}.conf
        src=/etc/nginx/sites-available/finance.{{ privacybox_domain }}.conf
        state=link
        force=yes
  notify: restart nginx

- name: Start php-fpm Service
  service: name=php7.3-fpm state=started enabled=yes
