---
- name: Install MariaDB package
  apt:
    pkg:
      - mariadb-server
      - libmariadbclient-dev
      - mariadb-client
    state: present

- name: Create MariaDB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Install the MySQL-python through pip
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - pip
    - MySQL-python

# Remove anonymous user account for localhost
- mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
