---
- name: Install MariaDB package
  apt: name={{ item }} state=present
  with_items:
   - mariadb-server

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
