parameters:
    database_driver: pdo_mysql
    database_driver_class: null
    database_host: 127.0.0.1
    database_port: {{ mysql_port }}
    database_name: {{ wb_db_name }}
    database_user: {{ wb_db_user }}
    database_password: {{ wb_db_password }}
    database_path: var/lib/mysql/wallabag
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: {{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: unix
    redis_host: localhost
    redis_port: 6379
    redis_path: /var/run/redis/redis.sock
    redis_password: null
    sites_credentials: {  }
    domain_name: 'https://wallabag.{{ privacybox_domain }}'
