---
- name: Installing prerequisites
  apt:
    pkg:
      - build-essential
      - python2.7-dev
      - libffi-dev
      - python-pip
      - python-setuptools
      - sqlite3
      - libssl-dev
      - python-virtualenv
      - libjpeg-dev
      - libxslt1-dev
    state: present

- name: Add an Apt signing key
  apt_key:
    url: https://matrix.org/packages/debian/repo-key.asc
    state: present

- lineinfile:
    path: /etc/apt/sources.list
    line: 'deb https://matrix.org/packages/debian/ stretch main'

- lineinfile:
    path: /etc/apt/sources.list
    line: 'deb-src https://matrix.org/packages/debian/ stretch main'

- name: Install Matrix Synapse package
  apt: pkg=matrix-synapse update_cache=yes state=present

- name: Copy Nextcloud server block
  template: src=nginx.conf dest=/etc/nginx/sites-available/matrix.{{ privacybox_domain_name }}.{{ privacybox_tld }}.conf

- name: setup nginx symlinks
  file: path=/etc/nginx/sites-enabled/matrix.{{ privacybox_domain_name }}.{{ privacybox_tld }}.conf
        src=/etc/nginx/sites-available/matrix.{{ privacybox_domain_name }}.{{ privacybox_tld }}.conf
        state=link
        force=yes
  notify: restart nginx
