---
- name: Enable apt-get HTTPS fetch.
  apt: name={{ item }} state=present
  with_items:
   - apt-transport-https
   - screen
   - ufw

- name: Install Python tools
  apt: name={{ item }} state=present
  with_items:
   - python-dev
   - python-pip

- name: Install some basic packages
  apt: name={{ item }} state=present
  with_items:
   - vim
   - git

- ufw:
    state: enabled
    rule: allow
    port: 22

- name: Reload ansible_facts
  setup:

# - local_action: copy content="test" dest=~/.privacybox/credentials
