---
- name: Enable apt-get HTTPS fetch.
  apt: name={{ item }} state=present
  with_items:
   - apt-transport-https
   - screen
   - ufw

- name: Install Python tools
  apt: name={{ item }} state=present
  with_items:
   - python-dev
   - python-pip

- name: Install some basic packages
  apt: name={{ item }} state=present
  with_items:
   - vim
   - git

- ufw:
    state: enabled
    rule: allow
    port: 22

- name: Create directory to hold SSL certificates
  file:
    path: /etc/ssl/private/{{ privacybox_domain }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

- name: create self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ privacybox_domain }}" -days 3650 -keyout /etc/ssl/private/{{ privacybox_domain }}/server.key -out /etc/ssl/private/{{ privacybox_domain }}/server.crt -extensions v3_ca creates=/etc/ssl/private/{{ privacybox_domain }}/server.crt

- name: Reload ansible_facts
  setup:

# - local_action: copy content="test" dest=~/.privacybox/credentials
