---
- name: add unstable packages for debian
  copy:
    src: etc/apt/sources.list.d/unstable.list
    dest: /etc/apt/sources.list.d/unstable.list
    owner: root
    group: root
    mode: 0644

- name: give unstable packages for debian a low priority
  copy:
    src: etc/apt/preferences.d/limit-unstable
    dest: /etc/apt/preferences.d/limit-unstable
    owner: root
    group: root
    mode: 0644

- name: ensure wireguard packages are installed
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  vars:
    packages:
      - wireguard
      - qrencode
